%%
% File:
%   generateScatter.m
%
% Author:
%   William Hammond (wth4280@g.rit.edu)
%
% Description:
%   This function generates and saves a scatter plot of the results of the
%   TV method
%
% Input: 
%   time - The number of time steps generated by the TV method
%   path - Path to data
function generateScatter(numNodes)
    pacing_sites = ['SEPTUMCENTER'; 'RVPOSTERIOR '; 'RVANTERIOR  '; 'LVLATEPI    '; 'LVLATENDO   '; 'LVLAT       '; 'LVANTERIOR  '];
    pacing_sites = cellstr(pacing_sites);
    
    x = 1:numNodes;
    x = x';
    
    for i = 1:length(pacing_sites)
        site = pacing_sites(i);
        site = site{1};
        file_in = strcat('inverse_potval_', site, '.mat');
        potvals = load(fullfile('Output', file_in));
        potvals = potvals.result;
        
        %% Plot at t = 5
        figure
        
        figure_title = strcat('Potentials at ', num2str(5), ' of ', site);
        scatter(x, potvals(:,5));
        title(figure_title)
        
        figure_title = strcat('Potentials_at_', num2str(5), '_of_', site);
        saveas(gcf, strcat(figure_title, '.png'));
        
        %% Plot at t = 15
        figure
        
        figure_title = strcat('Potentials at ', num2str(15), ' of ', site);
        scatter(x, potvals(:,15));
        title(figure_title)
        
        figure_title = strcat('Potentials_at_', num2str(15), '_of_', site);
        saveas(gcf, strcat(figure_title, '.png'));
        
        %% Plot at t = 30
        figure
        
        figure_title = strcat('Potentials at ', num2str(30), ' of ', site);
        scatter(x, potvals(:,30));
        title(figure_title)
        
        figure_title = strcat('Potentials_at_', num2str(30), '_of_', site);
        saveas(gcf, strcat(figure_title, '.png'));
        
        %% Plot at t = 40
        figure
        
        figure_title = strcat('Potentials at ', num2str(40), ' of ', site);
        scatter(x, potvals(:,40));
        title(figure_title)
        
        figure_title = strcat('Potentials_at_', num2str(40), '_of_', site);
        saveas(gcf, strcat(figure_title, '.png'));
    end
end